from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from sqlmodel import Session

from ai_world_cup.evaluation.tournament import build_tournament_leaderboard

START_MARKER = "<!-- leaderboard:start -->"
END_MARKER = "<!-- leaderboard:end -->"


def _escape_cell(value: object) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _percent(value: float) -> str:
    return f"{value:.1%}"


def _confidence(value: float) -> str:
    return f"{value:.2f}"


def build_readme_leaderboard_markdown(
    session: Session,
    *,
    limit: int = 10,
    completed_only: bool = True,
) -> str:
    rows = build_tournament_leaderboard(session, completed_only=completed_only)
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"_Generated by `aiwc readme leaderboard` on {generated_at}._",
        "",
    ]
    if not rows:
        lines.append("No valid tournament submissions have been imported yet.")
        return "\n".join(lines)

    lines.extend(
        [
            "| Rank | Model | Provider | Total | Group stage | Group standings | "
            "Knockout | Champion | Outcome acc. | Exact score acc. | Avg confidence |",
            "|---:|---|---|---:|---:|---:|---:|---|---:|---:|---:|",
        ]
    )
    for rank, row in enumerate(rows[:limit], start=1):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(rank),
                    _escape_cell(row.model_name),
                    _escape_cell(row.provider),
                    str(row.total_tournament_points),
                    str(row.group_stage_points),
                    str(row.group_standing_points),
                    str(row.knockout_points),
                    _escape_cell(row.champion_prediction),
                    _percent(row.outcome_accuracy),
                    _percent(row.exact_score_accuracy),
                    _confidence(row.average_confidence),
                ]
            )
            + " |"
        )
    if len(rows) > limit:
        lines.extend(["", f"Showing top {limit} of {len(rows)} models."])
    return "\n".join(lines)


def update_readme_leaderboard(
    session: Session,
    *,
    readme_path: Path,
    limit: int = 10,
    completed_only: bool = True,
) -> Path:
    markdown = build_readme_leaderboard_markdown(
        session,
        limit=limit,
        completed_only=completed_only,
    )
    block = f"{START_MARKER}\n{markdown}\n{END_MARKER}"
    text = readme_path.read_text(encoding="utf-8")

    if START_MARKER in text and END_MARKER in text:
        before, remainder = text.split(START_MARKER, 1)
        _, after = remainder.split(END_MARKER, 1)
        updated = f"{before}{block}{after}"
    else:
        insertion = (
            "\n\n## Current Tournament Leaderboard\n\n"
            f"{block}\n\n"
            "For the full interactive table and charts, open the website leaderboard page.\n"
        )
        anchor = "\n---\n\n## Scoring System"
        if anchor in text:
            updated = text.replace(anchor, insertion + anchor, 1)
        else:
            updated = text.rstrip() + insertion + "\n"

    readme_path.write_text(updated, encoding="utf-8")
    return readme_path
